apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config 
  namespace: default 
data:
  useJobForCleaning: "yes"
  storageClassMap: |-
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
