apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /mnt/disks/blkvol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 127.0.0.1
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Block
  storageClassName: local-storage
