kind: Pod
apiVersion: v1
metadata:
  name: test-pod-2
spec:
  containers:
  - name: test-pod
    image: alpine:3.6
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "trap 'exit' TERM; while true; do sleep 1; done"
    volumeMounts:
    - name: local
      mountPath: "/mnt"
  restartPolicy: "Never"
  securityContext:
    fsGroup: 4321
  volumes:
  - name: local
    persistentVolumeClaim:
      claimName: example-local-claim
