#
# right now, quay.io does not support schema v2
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-proxy-quay-io
  namespace: fuyecheng 
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    proxy:
      remoteurl: https://quay.io 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fuyecheng
  name: registry-proxy-quay-io
  labels:
    app: registry-proxy-quay-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-proxy-quay-io
  template:
    metadata:
      labels:
        app: registry-proxy-quay-io
    spec:
      containers:
      - name: registry
        image: registry:2
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: registry-proxy-quay-io
---
apiVersion: v1
kind: Service
metadata:
  name: registry-proxy-quay-io
  namespace: fuyecheng
  labels:
    app: registry-proxy-quay-io
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP 
    targetPort: 5000
  selector:
    app: registry-proxy-quay-io
