kind: Pod
apiVersion: v1
metadata:
  name: issue56163-pod
spec:
  containers:
  - name: test-pod
    image: alpine:3.6
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "trap 'exit' TERM; while true; do sleep 1; done"
    volumeMounts:
    - name: local
      mountPath: "/mnt"
  volumes:
  - name: local
    persistentVolumeClaim:
      claimName: issue56163-pvc
