apiVersion: v1
kind: PersistentVolume
metadata:
  name: issue56163-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 127.0.0.1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
