kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.2.137:6789
  # monitors: 192.168.2.128:6789,127.0.0.1:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: default
  adminSecretName: ceph-admin-secret
  userId: kube
  userSecretName: ceph-secret
  #  userSecretNamespace: default
  # fsType: xfs
  imageFormat: "2"
  imageFeatures: layering
# allowVolumeExpansion: true
