kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: alpine:3.6
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "trap 'exit' TERM; while true; do sleep 1; done"
    volumeDevices:
    - name: local
      devicePath: "/dev/blk1"
  restartPolicy: "Never"
  securityContext:
    fsGroup: 1234
  volumes:
  - name: local
    persistentVolumeClaim:
      claimName: example-local-claim
