kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: alpine:3.6
    command:
    - "/bin/sh"
    args:
    - "-c"
    # See https://superuser.com/a/1299463/290489.
    - "trap 'exit' TERM; while true; do touch /mnt/testfile; done"
    volumeMounts:
    - name: local
      mountPath: "/mnt"
  restartPolicy: "Never"
  securityContext:
    fsGroup: 1234
  volumes:
  - name: local
    persistentVolumeClaim:
      claimName: example-local-claim
