kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
    volume.kubernetes.io/selected-node: 127.0.0.1
    # pv.kubernetes.io/bound-by-controller: true
    pv.kubernetes.io/bind-completed: true
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
  # volumeName: fakepv
