kind: Pod
apiVersion: v1
metadata:
  name: test-pod-1
spec:
  containers:
  - name: test-pod-1
    image: alpine
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "trap exit EXIT; while true; do sleep 1; done"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - 127.0.0.1
