kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
