kind: Pod
apiVersion: v1
metadata:
  name: test-pod-readonly-2
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 9999"
    volumeMounts:
    - name: pvc
      mountPath: "/mnt"
      readOnly: true
  restartPolicy: "Never"
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: claim2
      readOnly: true
