#!/bin/bash
#
# Script to generate prometheus.yml.
#

# global
cat <<EOF
# This file is generated by $(basename $0) automatically at $(date).
global:
  evaluation_interval: 60s
  scrape_interval: 30s
  external_labels: {}
scrape_configs:
EOF

# kubelet
cat <<EOF
  - job_name: 'kubelet'
    static_configs:
      - targets:
EOF

kubectl get nodes -ogo-template='{{- range .items}}
      {{- .metadata.name }}{{ "\t" }}
      {{- range .status.addresses }}
          {{- .type }}={{ .address }}{{ "\t" }}
      {{- end }}{{"\n"}}
{{- end}}' | grep 'InternalIP=' | grep -P -o "\d+\.\d+\.\d+\.\d+" | while read -r line; do
   echo "        - '$line:10255'"
done
