apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
spec:
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      containers:
      - name: provisioner
        image: "quay.io/external_storage/local-volume-provisioner:v2.0.0"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: provisioner-config
          mountPath: /etc/provisioner/config 
          readOnly: true
        - name: discovery-vol
          mountPath: /mnt/disks
          readOnly: true
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      # If you want provisioner to use a kubeconfig file to access API server, instead of the default
      #  in-cluster config, then specify the following environment variable:
      # - name: KUBECONFIG
      #   value: /path/to/kubeconfig
      volumes:
      - name: provisioner-config
        configMap:
          name: local-provisioner-config
      - name: discovery-vol
        hostPath:
          path: /mnt/disks
      serviceAccount: local-storage-admin
