apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config 
  namespace: default 
data:
  storageClassMap: |-
    #
    # Populating entries with user provided disk discovery directories 
    # and mount directories per storage class.
    #
    # fast-disks:     
      # hostDir: /mnt/fast-disks
      # mountDir:  /mnt/fast-disks 
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
