apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
    volumes.kubernetes.io/keep-terminated-pod-volumes: "true"
    k8s.qiniu.com/cpu-overcommit-ratio: "2"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: 127.0.0.1
  name: 127.0.0.1
