apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy
  name: deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      annotations:
        foo: bar
      labels:
        app: deploy
    spec:
      containers:
      - name: test-pod-1
        image: alpine
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "trap exit EXIT; while true; do sleep 1;       done"
      restartPolicy: Always
