apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc
provisioner: csi-hostpath
# provisioner: csi-hostpath-wrong
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# parameters:
  # "cofyc-debug": "true"
